ERP/Controllers/EmployeeSalaryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Mvc;

namespace ERP.Controllers
{
    public class EmployeeSalaryController : Controller
    {
        //
        // GET: /EmployeeSalary/
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult GetList(int limit, int offset, string Name)
        {
            Business.Sys_EmployeeSalary Sys_EmployeeSalary = new Business.Sys_EmployeeSalary();
            StringBuilder sb = new StringBuilder();
            if (!string.IsNullOrEmpty(Name))
            {
                sb.Append(" and Name='" + Name + "'");
            }
            return Json(new { total = Sys_EmployeeSalary.GetUserAdminListCount(sb.ToString()), rows = Sys_EmployeeSalary.UserAdminList(limit, offset, sb.ToString()) }, JsonRequestBehavior.AllowGet);
        }


        public ActionResult Add() 
        {
            ViewData["SexListItems"] = GetSex();
            ViewData["GetMonthItems"] = GetMonthItems();
            return View();
        }

        [HttpPost]
        public ActionResult Add(Model.EmployeeSalary EmployeeSalary) 
        {
            ViewData["SexListItems"] = GetSex();
            ViewData["GetMonthItems"] = GetMonthItems();
            Business.Sys_EmployeeSalary Sys_EmployeeSalary = new Business.Sys_EmployeeSalary();
            Sys_EmployeeSalary.Add(EmployeeSalary);
            Response.Write("<script>parent.layer.closeAll();</script>");
            return View();
        }

        public ActionResult Edit() 
        {
            Business.Sys_EmployeeSalary Sys_EmployeeSalary = new Business.Sys_EmployeeSalary();
            Model.EmployeeSalary EmployeeSalary = Sys_EmployeeSalary.GetModel(Request["id"]);
            ViewData["SexListItems"] = GetSex(EmployeeSalary.Sex);
            ViewData["GetMonthItems"] = GetMonthItems(EmployeeSalary.Month.ToString());
            return View(EmployeeSalary);
        }

        [HttpPost]
        public ActionResult Edit(Model.EmployeeSalary EmployeeSalary)
        {
            Business.Sys_EmployeeSalary Sys_EmployeeSalary = new Business.Sys_EmployeeSalary();
            Sys_EmployeeSalary.Update(EmployeeSalary);
            ViewData["SexListItems"] = GetSex(EmployeeSalary.Sex);
            ViewData["GetMonthItems"] = GetMonthItems(EmployeeSalary.Month.ToString());
            Response.Write("<script>parent.layer.closeAll();</script>");
            return View();
        }

        public ActionResult Delete() 
        {
            Business.Sys_EmployeeSalary Sys_EmployeeSalary = new Business.Sys_EmployeeSalary();
            Sys_EmployeeSalary.Delete(Request["id"]);
            return Content("1");
        }

        public List<SelectListItem> GetMonthItems(string month="")
        {
            List<SelectListItem> deptSelectItems = new List<SelectListItem>();
            for (int i = 1; i <= 12; i++)
            {
                SelectListItem items = new SelectListItem();
                items.Text = i.ToString();
                items.Value = i.ToString();
                if (!string.IsNullOrEmpty(month))
                {
                    if (i == Convert.ToInt32(month))
                    {
                        items.Selected = true;
                    }
                }
             
                deptSelectItems.Add(items);
            }
            return deptSelectItems;
        }

        public List<SelectListItem> GetSex(string Sex="")
        {
            
            List<SelectListItem> deptSelectItems = new List<SelectListItem>();

            SelectListItem items = new SelectListItem();
            items.Text = "男";
            items.Value = "男";
            // items.Selected = true;
            deptSelectItems.Add(items);
            items = new SelectListItem();
            items.Text = "女";
            items.Value = "女";
           //items.Selected = true;
            deptSelectItems.Add(items);
            if (!string.IsNullOrEmpty(Sex))
            {
                if (Sex == "男")
                {
                    deptSelectItems[0].Selected = true;
                }
                else {
                    deptSelectItems[1].Selected = true;
                }
            }
            return deptSelectItems;
        }
	}
}

ERP/Views/EmployeeSalary/Add.cshtml
@model Model.EmployeeSalary
@{
    Layout = null;
}

@Styles.Render("~/bootstrap/css/bootstrap.css")
@Scripts.Render("~/Plugins/jQuery/jquery-2.2.3.min.js")
@*加载弹出层*@
@Scripts.Render("~/Thems/js/layer/layer.js")    @Scripts.Render("~/My97DatePicker/WdatePicker.js")
<script src="~/Scripts/jquery.valiedate.form.js"></script>
<script>
    function CheckFrom() {
        if ($("#Name").val() == "") {
            layer.msg('姓名不能为空');
            return false;
        }
        if ($("#age").val() == "") {
            layer.msg('姓名不能为空');
            return false;
        }
        //if (!isMyFloat(Basicsalary)) {
        //    layer.msg('基本工资输入格式不正确');
        //    return false;
        //}
        //if (!isMyFloat(Commission)) {
        //    layer.msg('提成输入格式不正确');
        //    return false;
        //}
        //if (!isMyFloat(Reward)) {
        //    layer.msg('奖金输入格式不正确');
        //    return false;
        //}
        //if (!isMyFloat(Punishment)) {
        //    layer.msg('罚款输入格式不正确');
        //    return false;
        //}
        //if (!isMyFloat(salary)) {
        //    layer.msg('薪水输入格式不正确');
        //    return false;
        //}
        return true;
    }
</script>
@using (Html.BeginForm("Add", "EmployeeSalary", FormMethod.Post, new { onsubmit = "return  CheckFrom()" }))
    {
    <div class="box-body">
        <br />
        <div class="form-group" style="height:30px;">
            <span for="inputEmail3" class="col-sm-2 control-label"><span style="color:red;">*</span>姓名</span>
            <div class="col-sm-4">
                @Html.TextBoxFor(m => m.Name, new { @class = "form-control" })
            </div>
            <span for="inputEmail3" class="col-sm-2 control-label"><span style="color:red;">*</span>性别</span>
            <div class="col-sm-5">
                @Html.DropDownListFor(m => m.Sex, ViewData["SexListItems"] as List<SelectListItem>, new { @class = "form-control" })
            </div>
            <span for="inputEmail3" class="col-sm-2 control-label"><span style="color:red;">*</span>年龄</span>
            <div class="col-sm-6">
                @Html.TextBoxFor(m => m.age, new { @class = "form-control" })
            </div>
            <span for="inputEmail3" class="col-sm-2 control-label"><span style="color:red;">*</span>入职时间</span>
            <div class="col-sm-6">
                @Html.TextBoxFor(m => m.InductionTime, new { @class = "form-control", onclick = "WdatePicker({ startDate: '%y-%M-%d ', dateFmt: 'yyyy-MM-dd ', alwaysUseStartDate: true , readOnly: true})" })
            </div>
            <span for="inputEmail3" class="col-sm-2 control-label"><span style="color:red;">*</span>基本工资</span>
            <div class="col-sm-6">
                @Html.TextBoxFor(m => m.Basicsalary, new { @class = "form-control" })
            </div>
            <span for="inputEmail3" class="col-sm-2 control-label"><span style="color:red;">*</span>提成</span>
            <div class="col-sm-6">
                @Html.TextBoxFor(m => m.Commission, new { @class = "form-control" })
            </div>
            <span for="inputEmail3" class="col-sm-2 control-label"><span style="color:red;">*</span>奖金</span>
            <div class="col-sm-6">
                @Html.TextBoxFor(m => m.Reward,  new { @class = "form-control" })
            </div>
            <span for="inputEmail3" class="col-sm-2 control-label"><span style="color:red;">*</span>罚款</span>
            <div class="col-sm-6">
                @Html.TextBoxFor(m => m.Punishment,  new { @class = "form-control" })
            </div>
            <span for="inputEmail3" class="col-sm-2 control-label"><span style="color:red;">*</span>工资</span>
            <div class="col-sm-6">
                @Html.TextBoxFor(m => m.salary,new { @class = "form-control" })
            </div>
            <span for="inputEmail3" class="col-sm-2 control-label"><span style="color:red;">*</span>月份</span>
            <div class="col-sm-6">
                @Html.DropDownListFor(m => m.Month, ViewData["GetMonthItems"] as List<SelectListItem>, new { @class = "form-control" })
            </div>
            <span for="inputEmail3" class="col-sm-2 control-label"><span style="color:red;">*</span>备注</span>
            <div class="col-sm-6">
                @Html.TextAreaFor(m => m.Remark, new { @class = "form-control" })
            </div>
        </div>
    </div>
    <!-- /.box-body -->
    <div class="box-footer" style="text-align: center; margin-top: 610px; ">
        <button id="btn_add" type="submit"  class="btn btn-default">
            <span class="glyphicon glyphicon-saved" aria-hidden="true"></span>保存
        </button>
        <button id="btn_delete" type="button" class="btn btn-default" onclick="parent.layer.closeAll();" style="margin-left:25px;">
            <span class="glyphicon glyphicon-random" aria-hidden="true"></span>&nbsp;&nbsp;取消
        </button>
    </div>
}

ERP/Views/EmployeeSalary/Edit.cshtml
@model Model.EmployeeSalary
@{
    Layout = null;
}

@Styles.Render("~/bootstrap/css/bootstrap.css")
@Scripts.Render("~/Plugins/jQuery/jquery-2.2.3.min.js")
@*加载弹出层*@
@Scripts.Render("~/Thems/js/layer/layer.js")    @Scripts.Render("~/My97DatePicker/WdatePicker.js")
<script src="~/Scripts/jquery.valiedate.form.js"></script>
<script>
    function CheckFrom() {
        if ($("#Name").val() == "") {
            layer.msg('姓名不能为空');
            return false;
        }
        if ($("#age").val() == "") {
            layer.msg('姓名不能为空');
            return false;
        }
        //if (!isMoney(Basicsalary)) {
        //    layer.msg('基本工资输入格式不正确');
        //    return false;
        //}
        //if (!isMoney(Commission)) {
        //    layer.msg('提成输入格式不正确');
        //    return false;
        //}
        //if (!isMoney(Reward)) {
        //    layer.msg('奖金输入格式不正确');
        //    return false;
        //}
        //if (!isMoney(Punishment)) {
        //    layer.msg('罚款输入格式不正确');
        //    return false;
        //}
        //if (!isMoney(salary)) {
        //    layer.msg('薪水输入格式不正确');
        //    return false;
        //}
        return true;
    }
</script>
@using (Html.BeginForm("Edit", "EmployeeSalary", FormMethod.Post, new { onsubmit = "return  CheckFrom()" }))
{
    <div class="box-body">
        <br />
        <div class="form-group" style="height:30px;">
            <span for="inputEmail3" class="col-sm-2 control-label"><span style="color:red;">*</span>姓名</span>
            <div class="col-sm-4">
                @Html.TextBoxFor(m => m.Name, new { @class = "form-control" })
            </div>
            <span for="inputEmail3" class="col-sm-2 control-label"><span style="color:red;">*</span>性别</span>
            <div class="col-sm-5">
                @Html.DropDownListFor(m => m.Sex, ViewData["SexListItems"] as List<SelectListItem>, new { @class = "form-control" })
            </div>
            <span for="inputEmail3" class="col-sm-2 control-label"><span style="color:red;">*</span>年龄</span>
            <div class="col-sm-6">
                @Html.TextBoxFor(m => m.age, new { @class = "form-control" })
            </div>
            <span for="inputEmail3" class="col-sm-2 control-label"><span style="color:red;">*</span>入职时间</span>
            <div class="col-sm-6">
                @Html.TextBoxFor(m => m.InductionTime, new { @class = "form-control" , onclick = "WdatePicker({ startDate: '%y-%M-%d ', dateFmt: 'yyyy-MM-dd ', alwaysUseStartDate: true , readOnly: true})" })
            </div>
            <span for="inputEmail3" class="col-sm-2 control-label"><span style="color:red;">*</span>基本工资</span>
            <div class="col-sm-6">
                @Html.TextBoxFor(m => m.Basicsalary, new { @class = "form-control" })
            </div>
            <span for="inputEmail3" class="col-sm-2 control-label"><span style="color:red;">*</span>提成</span>
            <div class="col-sm-6">
                @Html.TextBoxFor(m => m.Commission, new { @class = "form-control" })
            </div>
            <span for="inputEmail3" class="col-sm-2 control-label"><span style="color:red;">*</span>奖金</span>
            <div class="col-sm-6">
                @Html.TextBoxFor(m => m.Reward, new { @class = "form-control" })
            </div>
            <span for="inputEmail3" class="col-sm-2 control-label"><span style="color:red;">*</span>罚款</span>
            <div class="col-sm-6">
                @Html.TextBoxFor(m => m.Punishment, new { @class = "form-control" })
            </div>
            <span for="inputEmail3" class="col-sm-2 control-label"><span style="color:red;">*</span>工资</span>
            <div class="col-sm-6">
                @Html.TextBoxFor(m => m.salary, new { @class = "form-control" })
            </div>
            <span for="inputEmail3" class="col-sm-2 control-label"><span style="color:red;">*</span>月份</span>
            <div class="col-sm-6">
                @Html.DropDownListFor(m => m.Month, ViewData["GetMonthItems"] as List<SelectListItem>, new { @class = "form-control" })
            </div>
            <span for="inputEmail3" class="col-sm-2 control-label"><span style="color:red;">*</span>备注</span>
            <div class="col-sm-6">
                @Html.TextBoxFor(m => m.Remark, new { @class = "form-control" })
                @Html.HiddenFor(x=>x.ID)
            </div>
        </div>
    </div>
    <!-- /.box-body -->
    <div class="box-footer" style="text-align: center; margin-top: 610px; ">
        <button id="btn_add" type="submit" class="btn btn-default">
            <span class="glyphicon glyphicon-saved" aria-hidden="true"></span>保存
        </button>
        <button id="btn_delete" type="button" class="btn btn-default" onclick="parent.layer.closeAll();" style="margin-left:25px;">
            <span class="glyphicon glyphicon-random" aria-hidden="true"></span>&nbsp;&nbsp;取消
        </button>
    </div>
}

ERP/Views/EmployeeSalary/Index.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
    @*加载表格*@
    @Scripts.Render("~/plugins/jQuery/jquery-2.2.3.min.js")

    @Styles.Render("~/Bootstrap/css/bootstrap.css")
    @Scripts.Render("~/Bootstrap/js/bootstrap.js")

    @Styles.Render("~/Bootstrap/bootstrap-table/bootstrap-table.css")
    @Scripts.Render("~/Bootstrap/bootstrap-table/bootstrap-table.js")
    @*加载弹出层*@
    @Scripts.Render("~/Thems/js/layer/layer.js")
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.5.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/ionicons/2.0.1/css/ionicons.min.css">

    <script src="~/Scripts/Admin/EmployeeSalary.js"></script>

</head>
<body>
    <div class="panel-body" style="padding-bottom:0px;">
        <div class="panel panel-default">
            <div class="panel-heading">员工工资列表</div>
            <div class="panel-body">
                <form id="formSearch" class="form-horizontal">
                    <div class="form-group">
                        <label class="control-label col-sm-2" for="txt_search_departmentname">
                            姓名
                        </label>
                        <div class="col-sm-2">
                            <input type="text" class="form-control" id="Name">
                        </div>
                        <div class="col-sm-4" style="text-align:left;">
                            <button type="button" class="btn btn-default" onclick="onloadTable();">
                                查询 <span class="glyphicon glyphicon-search" aria-hidden="true"></span>
                            </button>
                        </div>
                    </div>
                </form>
            </div>
        </div>

        <div id="toolbar" class="btn-group">
            <button id="btn_add" type="button" class="btn btn-default">
                <span class="glyphicon glyphicon-plus" aria-hidden="true"></span> 添加
            </button>
            <button id="btn_edit" type="button" class="btn btn-default">
                <span class="glyphicon glyphicon-edit" aria-hidden="true"></span> 修改
            </button>
            <button id="btn_delete" type="button" class="btn btn-default">
                <span class="glyphicon glyphicon-remove" aria-hidden="true"></span> 删除
            </button>
        </div>
        <table id="tb_departments" data-reorderable-columns="true"></table>
    </div>
    <script>
        $(function () {
            onloadTable();
            $("#btn_add").click(function () {
                parent.layer.open({
                    type: 2,
                    title: '增加',
                    shadeClose: true,
                    shade: 0.8,
                    area: ['300px;', '600px;'],
                    content: '/EmployeeSalary/Add',
                    end: function () { //层彻底关闭后执行的回调
                        onloadTable();
                    }
                });
            });
            $("#btn_edit").click(function () {
                var ids = $("#tb_departments").bootstrapTable('getSelections');
                if (ids.length == 0) {
                    parent.layer.msg('请先选中一行');
                    return false;
                }
                parent.layer.open({
                    type: 2,
                    title: '修改',
                    shadeClose: true,
                    shade: 0.8,
                    area: ['250px;', '600px;'],
                    content: '/EmployeeSalary/Edit?id=' + ids[0].ID,
                    end: function () { //层彻底关闭后执行的回调
                        onloadTable();
                    }
                });
            });
            $("#btn_delete").click(function () {
                var ids = $("#tb_departments").bootstrapTable('getSelections');
                if (ids.length == 0) {
                    parent.layer.msg('请先选中一行');
                    return false;
                }
                parent.layer.confirm('删除当前管理员?', {
                    btn: ['确定', '取消'] //按钮
                }, function () {
                    $.ajax({
                        url: '/EmployeeSalary/Delete?id=' + ids[0].ID,
                        async: false,
                        success: function (data) { 
                            parent.layer.closeAll();
                            onloadTable();
             
                        }
                    })

                }, function () {
                });
            });
        })
    </script>
</body>
</html>