ERP/Controllers/UserInfoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Mvc;

namespace ERP.Controllers
{
    public class UserInfoController : LoginFilter
    {
        //
        // GET: /UserInfo1/
        public ActionResult Index()
        {
            ViewData["deptSelectItems"] = GetdeptSelectItems();
            ViewData["UsersSelectItems"] = GetUserInfoSelectItems();
            return View();
        }

        /// <summary>
        /// 分页获得数据信息
        /// </summary>
        /// <param name="limit">页码大小</param>
        /// <param name="offset">从第几条数据开始</param>
        /// <param name="UserName">用户名</param>
        /// <param name="Role">角色ID</param>
        /// <returns></returns>
        public JsonResult GetUserList(int limit, int offset, string UserName, string SelectItem, string UsersSelectItems)
        {
            Business.Sys_UserAdmin Sys_UserAdmin = new Business.Sys_UserAdmin();
            StringBuilder sb = new StringBuilder();
            if (!string.IsNullOrEmpty(UserName))
            {
                sb.Append(" and UserName='" + UserName + "'");
            }
            if (!string.IsNullOrEmpty(SelectItem))
            {
                 sb.Append(" and RoleCode='" + SelectItem + "'");
            }
            if (!string.IsNullOrEmpty(UsersSelectItems))
            {
                sb.Append(" and  charindex(',"+UsersSelectItems+",',','+cast(WorkUsersId as varchar)+','  )>0 ");
            }
        
            return Json(new { total = Sys_UserAdmin.GetUserAdminListCount(sb.ToString()), rows = Sys_UserAdmin.UserAdminList(limit, offset, sb.ToString()) }, JsonRequestBehavior.AllowGet);
        }   
        /// <summary>
        /// 修改状态是否启用
        /// </summary>
        /// <returns></returns>
        public ActionResult UpdateUserAdminIsEnable()
        {
            int Enable = int.Parse(Request["Enable"]);
            Enable = Enable == 0 ? 1 : Enable == 1 ? 0 : Enable;
            int ID = int.Parse(Request["ID"]);
            Business.Sys_UserAdmin Sys_UserAdmin = new Business.Sys_UserAdmin();
            if (Sys_UserAdmin.UpdateUserAdminIsEnable(Enable, ID))
            {
                return Content("True");
            }
            return Content("False");
        }
        /// <summary>
        /// 删除一个会员
        /// </summary>
        /// <returns></returns>
        public ActionResult DeleteUserAdminInfo()
        {
            ViewData["deptSelectItems"] = GetdeptSelectItems();          
            string ids = Request["UsersId"];
            try
            {
                string strwhere = "and id in(" + ids + ")";
                Business.Sys_UserAdmin Sys_UserAdmin = new Business.Sys_UserAdmin();
                List<Model.UserAdmin> list = Sys_UserAdmin.GetUserAdminList(strwhere);
                foreach (var item in list)
                {
                    Sys_UserAdmin.DeleteUserAdminInfo(item.ID);                    
                }
                return Content("True");
            }
            catch (Exception ex)
            {
                return Content("False");
            }
        }

        public ActionResult Edit()
        {
            ViewData["deptSelectItems"] = GetdeptSelectItems();
            int UserAdminId = int.Parse(Request["UserAdminId"]);
            Business.Sys_UserAdmin Sys_UserAdmin = new Business.Sys_UserAdmin();
            return View(Sys_UserAdmin.GetUserAdminByUserId(UserAdminId));
        }

        public ActionResult EditInfo(Model.UserAdmin UserAdmin)
        {
            ViewData["deptSelectItems"] = GetdeptSelectItems();
            Business.Sys_UserAdmin Sys_UserAdmin = new Business.Sys_UserAdmin(); 
            Business.Sys_Role Sys_Role = new Business.Sys_Role();
            UserAdmin.PassWord = Utility.ChangeText.md5(UserAdmin.PassWord);
            UserAdmin.RoleName = Sys_Role.GetRoleInfoByRoleCode(UserAdmin.RoleCode).RoleName;
            if (Sys_UserAdmin.UpdateUserAdmin(UserAdmin))
            {
                return Content("1");
            }
            return Content("0");
        }

        public ActionResult Add()
        {
            ViewData["deptSelectItems"] = GetdeptSelectItems();
            return View();
        }


        public ActionResult AddInfo(Model.UserAdmin UserAdmin)
        {
            ViewData["deptSelectItems"] = GetdeptSelectItems();
            Business.Sys_UserAdmin Sys_UserAdmin = new Business.Sys_UserAdmin();
            Business.Sys_Role Sys_Role = new Business.Sys_Role();           
            UserAdmin.RoleName=Sys_Role.GetRoleInfoByRoleCode(UserAdmin.RoleCode).RoleName;
            UserAdmin.PassWord = Utility.ChangeText.md5(UserAdmin.PassWord);
            if (Sys_UserAdmin.InsertUserAdmin(UserAdmin))
            {
                return Content("1");
            }
            return Content("0");
        }


        /// <summary>
        /// 验证管理员账号是否存在
        /// </summary>
        /// <returns></returns>
        public ActionResult CheckUserAdminInfo()
        {
            string UserName = Request["UserName"];
            Business.Sys_UserAdmin Sys_UserAdmin = new Business.Sys_UserAdmin();
            if (Sys_UserAdmin.CheckUserAdminInfo(UserName))
            {
                return Content("True");
            }
            return Content("False");
        }

        public ActionResult SetRoleInfo() 
        {
            ViewData["SetRoleInfoId"] = Request["SetRoleInfoId"];
            ViewData["deptSelectItems"] = GetdeptSelectItems();
        

            return View();
        }


        [HttpPost]
        public ActionResult SetRoleInfo(string deptSelectItems)
        {
            ViewData["SetRoleInfoId"] = Request["SetRoleInfoId"];
            ViewData["deptSelectItems"] = GetdeptSelectItems();
            string RoleCode = Request["deptSelectItems"];
            Business.Sys_Role Sys_Role = new Business.Sys_Role();
            Model.RoleInfo RoleInfo = Sys_Role.GetRoleInfoByRoleCode(RoleCode);
            string SetRoleInfoId = Request["SetRoleInfoId"];
            Business.Sys_UserAdmin Sys_UserAdmin = new Business.Sys_UserAdmin();        
            if (Sys_UserAdmin.SetUserAdminRole(SetRoleInfoId, RoleInfo.RoleCode, RoleInfo.RoleName))
            {
               
            }
            Response.Write("<script>parent.layer.closeAll();</script>");
            return View();
        }

        public List<SelectListItem> GetUserInfoSelectItems() 
        {
            Business.Sys_UserAdmin Sys_UserAdmin = new Business.Sys_UserAdmin();
            List<Model.UserAdmin>  list= Sys_UserAdmin.GetUserAdminListByRoleCodeNo("Customer");
            List<SelectListItem> deptSelectItems = new List<SelectListItem>();
            SelectListItem item = new SelectListItem();
            item.Text = "-请选择-";
            item.Value = "";
            item.Selected = true;
            deptSelectItems.Add(item);
            foreach (Model.UserAdmin d in list)
            {
                item = new SelectListItem();
                item.Text = d.RealName;
                item.Value = d.ID.ToString();
                item.Selected = false;
                deptSelectItems.Add(item);
            }
            return deptSelectItems;
        }
        public List<SelectListItem> GetdeptSelectItems()
        {
            Business.Sys_Role Sys_Role = new Business.Sys_Role();
            List<Model.RoleInfo> RoleInfoList = Sys_Role.UserRoleList();
            List<SelectListItem> deptSelectItems = new List<SelectListItem>();
            SelectListItem item = new SelectListItem();
            item.Text = "-请选择-";
            item.Value = "";
            item.Selected = true;
            deptSelectItems.Add(item);
            foreach (Model.RoleInfo d in RoleInfoList)
            {
                item = new SelectListItem();
                item.Text = d.RoleName;
                item.Value = d.RoleCode.ToString();
                item.Selected = false;
                deptSelectItems.Add(item);
            }
            return deptSelectItems;
        }


        public ActionResult SetWorkRealName() 
        {
            ViewData["id"] = Request["id"];
            //ViewData["UserInfoList"]=
            return View(GetUserSelectItems(int.Parse(Request["id"])));
        }

        [HttpPost]
        public ActionResult SetWorkRealName(string id, string deptSelectItems, string SelectRealName) 
        {
            ViewData["id"] = Request["id"];
            deptSelectItems = Request["deptSelectItems"];
            SelectRealName = Request["SelectRealName"];
            Business.Sys_UserAdmin Sys_UserAdmin = new Business.Sys_UserAdmin();
            Sys_UserAdmin.SetWorkName(id, SelectRealName, deptSelectItems);
            Response.Write("<script>parent.layer.closeAll();</script>");
            return View(GetUserSelectItems(int.Parse(Request["id"])));
        }

        public List<Model.UserAdmin> GetUserSelectItems(int  id)
        {
            Business.Sys_UserAdmin Sys_UserAdmin = new Business.Sys_UserAdmin();
            List<Model.UserAdmin> list = Sys_UserAdmin.GetUserAdminListByRoleCodeNo("Customer");
            Model.UserAdmin useradmin = Sys_UserAdmin.GetUserAdminByUserId(id);
            if (string.IsNullOrEmpty(useradmin.WorkUsersId))
            {
                return list;
            }
            string[] checkList = useradmin.WorkUsersId.Split(',');
            string msg = string.Empty;

            
           
            return Sys_UserAdmin.GetUserAdminListByRoleCodeNo("Customer");
            //List<SelectListItem> deptSelectItems = new List<SelectListItem>();
            //SelectListItem item = new SelectListItem();
            //foreach (Model.UserAdmin d in UserAdminList)
            //{
            //    item = new SelectListItem();
            //    item.Text = d.RealName;
            //    item.Value = d.ID.ToString();

ERP/Views/UserInfo/Add.cshtml
@model Model.UserAdmin
@{
    Layout = null;
}

@Styles.Render("~/bootstrap/css/bootstrap.css")
@Scripts.Render("~/Plugins/jQuery/jquery-2.2.3.min.js")
@*加载弹出层*@
@Scripts.Render("~/Thems/js/layer/layer.js")
<script src="~/Scripts/jquery.valiedate.form.js"></script>
<script>
    function CheckFrom()
    {
        if ($("#UserName").val()=="") {
            layer.msg('用户账号不能为空');
            return false;
        }
        if (!checknum($("#UserName").val())) {
            layer.msg('用户账号只能是字母或者数字');
            return false;
        }
        if ($("#PassWord").val() == "") {
            layer.msg('密码不能为空');
            return false;
        }
        if ($("#OwnedCompany").val() == "") {
            layer.msg('所属公司不能为空');
            return false;
        }
        if ($("#RoleCode").find("option:selected").val() == "") {
            layer.msg('请选择一个角色');
            return false;
        }

        var CheckUserInfo = true;
        $.ajax({
            url: '/UserInfo/CheckUserAdminInfo?UserName=' + $("#UserName").val(),
            async:false,
            success: function (data)
            {
                if (data == "True") {
                    CheckUserInfo = false;                
                }           
            }
        })
        if (CheckUserInfo==false) {
            layer.msg('管理员姓名已经存在');
            return false;
        }
        $.ajax({
            url: '/UserInfo/AddInfo',
            data: $("#formInfo").serialize(),
            success: function (data)
            {
                parent.layer.closeAll();
            }
        })
        return true;
    }
</script>
<form id="formInfo">
    <div class="box-body">
        <br />
        <div class="form-group" style="height:30px;">
            <span for="inputEmail3" class="col-sm-2 control-label"><span style="color:red;">*</span>管理员账号&nbsp;&nbsp;&nbsp;&nbsp;</span>
            <div class="col-sm-4">
                @Html.TextBoxFor(m => m.UserName, new { @class = "form-control" })
            </div>
            <span for="inputEmail3" class="col-sm-2 control-label"><span style="color:red;">*</span>密码</span>
            <div class="col-sm-5">
                @Html.PasswordFor(m => m.PassWord, new { @class = "form-control" })
            </div>
            <span for="inputEmail3" class="col-sm-2 control-label"><span style="color:red;">*</span>真实姓名</span>
            <div class="col-sm-6">
                @Html.TextBoxFor(m => m.RealName, new { @class = "form-control" })
            </div>
            <span for="inputEmail3" class="col-sm-2 control-label"><span style="color:red;">*</span>所属公司</span>
            <div class="col-sm-6">
                @Html.TextBoxFor(m => m.OwnedCompany, new { @class = "form-control" })
            </div>
            <span for="inputEmail3" class="col-sm-2 control-label"><span style="color:red;">*</span>角色</span>
            <div class="col-sm-6">
                @Html.DropDownListFor(m => m.RoleCode, ViewData["deptSelectItems"] as List<SelectListItem>, new { @class = "form-control" })
            </div>
        </div>
    </div>
    <!-- /.box-body -->
    <div class="box-footer" style="text-align: center;margin-top:250px;">
        <button id="btn_add" type="button"  onclick="CheckFrom()" class="btn btn-default">
            <span class="glyphicon glyphicon-saved" aria-hidden="true"></span>保存
        </button>
        <button id="btn_delete" type="button" class="btn btn-default" onclick="parent.layer.closeAll();" style="margin-left:25px;">
            <span class="glyphicon glyphicon-random" aria-hidden="true"></span>&nbsp;&nbsp;取消
        </button>
    </div>

</form>

ERP/Views/UserInfo/AddLogoPhoto.cshtml
@{
    Layout = null;
}

@Styles.Render("~/bootstrap/css/bootstrap.css")
@Scripts.Render("~/Plugins/jQuery/jquery-2.2.3.min.js")
@*加载弹出层*@
@Scripts.Render("~/Thems/js/layer/layer.js")
<script src="~/Scripts/jquery.valiedate.form.js"></script>
<script>
    //验证附件类型
    function AttachValid(id) {
        var result = true;
        var oFile = document.getElementById(id);
        if (oFile.value == null || oFile.value == "") {
            return false;
        }
        return true;
    }

    function CheckFrom()
    {
        if (!AttachValid("attach_path")) {
            parent.layer.msg('请上传附件');
            return false;
        }
    }
</script>
@using (Html.BeginForm("AddLogoPhoto", "UserInfo", FormMethod.Post, new { onsubmit = "return  CheckFrom()", enctype = "multipart/form-data" }))
{
    <div class="box-body">
        <br />
        <div class="form-group" style="height:30px;">
           <input type="hidden"  id="id"  name="id"  value="@ViewData["id"]"/>
            <span for="inputEmail3" class="col-sm-2 control-label"><span style="color:red;">*</span>Logo图片</span>
            <div class="col-sm-6">
                <input type="file" class="form-control" id="attach_path" name="attach_path" />
            </div>
            <input type="hidden" value="@ViewData["success"]" id="success" />

        </div>
    </div>
                    <!-- /.box-body -->
    <div class="box-footer" style="text-align: center;margin-top:35px;">
        <button id="btn_add" type="submit" class="btn btn-default">
            <span class="glyphicon glyphicon-saved" aria-hidden="true"></span>保存
        </button>
        <button id="btn_delete" type="button" class="btn btn-default" onclick="parent.layer.closeAll();" style="margin-left:25px;">
            <span class="glyphicon glyphicon-random" aria-hidden="true"></span>&nbsp;&nbsp;取消
        </button>
    </div>
}

ERP/Views/UserInfo/Edit.cshtml
@model Model.UserAdmin
@{
    Layout = null;
}

@Styles.Render("~/bootstrap/css/bootstrap.css")
@Scripts.Render("~/Plugins/jQuery/jquery-2.2.3.min.js")
@*加载弹出层*@
@Scripts.Render("~/Thems/js/layer/layer.js")
<script src="~/Scripts/jquery.valiedate.form.js"></script>
<script>
    function CheckFrom() {
        if ($("#PassWord").val() == "") {
            layer.msg('密码不能为空');
            return false;
        }
        if ($("#OwnedCompany").val() == "") {
            layer.msg('所属公司不能为空');
            return false;
        }
        if ($("#RoleCode").find("option:selected").val() == "") {
            layer.msg('请选择一个角色');
            return false;
        }
        $.ajax({
            url: '/UserInfo/EditInfo',
            data: $("#formInfo").serialize(),
            success: function (data) {
                parent.layer.closeAll();
            }
        })
        return true;
    }
</script>
<form id="formInfo">
    <div class="box-body">
        <br />
        <div class="form-group" style="height:30px;">

                @Html.HiddenFor(m => m.ID)

            <span for="inputEmail3" class="col-sm-2 control-label"><span style="color:red;">*</span>密码</span>
            <div class="col-sm-5">
                @Html.PasswordFor(m => m.PassWord, new { @class = "form-control" })
            </div>
            <span for="inputEmail3" class="col-sm-2 control-label"><span style="color:red;">*</span>真实姓名</span>
            <div class="col-sm-6">
                @Html.TextBoxFor(m => m.RealName, new { @class = "form-control" })
            </div>
            <span for="inputEmail3" class="col-sm-2 control-label"><span style="color:red;">*</span>所属公司</span>
            <div class="col-sm-6">
                @Html.TextBoxFor(m => m.OwnedCompany, new { @class = "form-control" })
            </div>
            <span for="inputEmail3" class="col-sm-2 control-label"><span style="color:red;">*</span>角色</span>
            <div class="col-sm-6">
                @Html.DropDownListFor(m => m.RoleCode, ViewData["deptSelectItems"] as List<SelectListItem>, new { @class = "form-control" })
            </div>
        </div>
    </div>
    <!-- /.box-body -->
    <div class="box-footer" style="text-align: center;margin-top:250px;">
        <button id="btn_add" type="button" onclick="CheckFrom()" class="btn btn-default">
            <span class="glyphicon glyphicon-saved" aria-hidden="true"></span>保存
        </button>
        <button id="btn_delete" type="button" class="btn btn-default" onclick="parent.layer.closeAll();" style="margin-left:25px;">
            <span class="glyphicon glyphicon-random" aria-hidden="true"></span>&nbsp;&nbsp;取消
        </button>
    </div>

</form>

ERP/Views/UserInfo/Index.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title> 
    @Styles.Render("~/Bootstrap/css/bootstrap.css")   
    @Styles.Render("~/Bootstrap/bootstrap-table/bootstrap-table.css")    
</head>
<body>
    <div class="panel-body" style="padding-bottom:0px;">
        <div class="panel panel-default">
            <div class="panel-heading">用户列表</div>
            <div class="panel-body">
                <form id="formSearch" class="form-horizontal">
                    <div class="form-group">
                        <label class="control-label col-sm-2" for="txt_search_departmentname">
                            账号
                        </label>
                        <div class="col-sm-2">
                            <input type="text" class="form-control" id="UserNameText">
                        </div>
                        <label class="control-label col-sm-2" for="txt_search_departmentname">
                            角色
                        </label>
                        <div class="col-sm-2">
                            @Html.DropDownList("deptSelectItems", ViewData["deptSelectItems"] as List<SelectListItem>, new { @class = "form-control" })
                        </div>
                        <label class="control-label col-sm-2" for="txt_search_departmentname">
                            业务对应负责人
                        </label>
                        <div class="col-sm-2">
                            @Html.DropDownList("UsersSelectItems", ViewData["UsersSelectItems"] as List<SelectListItem>, new { @class = "form-control" })
                        </div>
                        <div class="col-sm-4" style="text-align:left;">
                            <button type="button" class="btn btn-default" onclick="onloadTable();">
                                查询 <span class="glyphicon glyphicon-search" aria-hidden="true"></span>
                            </button>
                        </div>
                    </div>
                </form>
            </div>
        </div>

        <div id="toolbar" class="btn-group">
            <button id="btn_add" type="button" class="btn btn-default">
                <span class="glyphicon glyphicon-plus" aria-hidden="true"></span> 添加
            </button>
            <button id="btn_edit" type="button" class="btn btn-default">
                <span class="glyphicon glyphicon-edit" aria-hidden="true"></span> 修改
            </button>
            <button id="btn_delete" type="button" class="btn btn-default">
                <span class="glyphicon glyphicon-remove" aria-hidden="true"></span> 删除
            </button>
        </div>
        <table id="tb_departments" data-reorderable-columns="true"></table>
    </div>
    @*加载表格*@
    @Scripts.Render("~/plugins/jQuery/jquery-2.2.3.min.js")
    @Scripts.Render("~/Bootstrap/js/bootstrap")
    @*加载弹出层*@
    @Scripts.Render("~/Thems/js/layer/layer.js")
    <script src="~/Scripts/Admin/UserInfo.js?v=1"></script>
    <script>
        $(function () {
            onloadTable();
            $("#btn_add").click(function () {
                parent.layer.open({
                    type: 2,
                    title: '增加管理员',
                    shadeClose: true,
                    shade: 0.8,
                    area: ['300px;', '400px;'],
                    content: '/UserInfo/Add',
                    end: function () { //层彻底关闭后执行的回调
                        onloadTable();
                    }
                });
            });
            $("#btn_edit").click(function () {
                var ids = $("#tb_departments").bootstrapTable('getSelections');
                if (ids.length == 0) {
                    parent.layer.msg('请先选中一行');
                    return false;
                }
                parent.layer.open({
                    type: 2,
                    title: '修改管理员',
                    shadeClose: true,
                    shade: 0.8,
                    area: ['250px;', '400px;'],
                    content: '/UserInfo/Edit?UserAdminId=' + ids[0].ID,
                    end: function () { //层彻底关闭后执行的回调
                        onloadTable();
                    }
                });
            });
            $("#btn_delete").click(function () {
                var ids = $("#tb_departments").bootstrapTable('getSelections');
                if (ids.length == 0) {
                    parent.layer.msg('请先选中一行');
                    return false;
                }
                parent.layer.confirm('确定删除当前用户吗?', {
                    btn: ['确定', '取消'] //按钮
                }, function () {
                    var id = '';
                    for (var i = 0; i < ids.length; i++) {
                        id += ids[i].ID + ",";
                    }
                    id = id.substr(0, id.length - 1);
                    $.ajax({
                        url: '/UserInfo/DeleteUserAdminInfo?UsersId=' + id,
                        async: false,
                        success: function (data) {
                            parent.layer.closeAll();
                            onloadTable();
                           // parent.layer.closeAll();
                        }
                    })

                }, function () {
                });
            });
        })

        function EditIsEnable(ID, IsEnable) {
            layer.confirm('确定修改当前状态?', {
                btn: ['确定', '取消'] //按钮
            }, function () {
                $.ajax({
                    url: '/UserInfo/UpdateUserAdminIsEnable?Enable=' + IsEnable + '&ID=' + ID,
                    async: false,
                    success: function (data) {
                        if (data == "True") {
                            layer.msg('修改成功');
                            onloadTable();
                        }
                        else {
                            layer.msg('修改失败');
                        }
                    }
                })

            }, function () {
            });
        }

        function SetRoleInfo(id)
        {
            parent.layer.open({
                type: 2,
                title: '设置角色',
                shadeClose: true,
                shade: 0.8,
                area: ['250px;', '200px;'],
                content: '/UserInfo/SetRoleInfo?SetRoleInfoId=' + id,
                end: function () { //层彻底关闭后执行的回调
                    onloadTable();
                }
            });
        }

        function SetWorkRealName(id)
        {
            parent.layer.open({
                type: 2,
                title: '设置工作负责人',
                shadeClose: true,
                shade: 0.8,
                //area: ['250px;', '230px;'],
                content: '/UserInfo/SetWorkRealName?id=' + id,
                end: function () { //层彻底关闭后执行的回调
                    onloadTable();
                }
            });
        }
        function AddLogoPhoto(id)
        {
            parent.layer.open({
                type: 2,
                title: '添加logo图标',
                shadeClose: true,
                shade: 0.8,
                //area: ['250px;', '230px;'],
                content: '/UserInfo/AddLogoPhoto?id=' + id,
                end: function () { //层彻底关闭后执行的回调
                    onloadTable();
                }
            });

        }

        function SetWeekly(id)
        {
            parent.layer.open({
                type: 2,
                title: '设置周次',
                shadeClose: true,
                shade: 0.8,
                area: ['300px;', '400px;'],
                content: '/UserInfo/SetWeekly?id=' + id,
                end: function () { //层彻底关闭后执行的回调
                    onloadTable();
                }
            });
        }
    </script>
</body>
</html>

ERP/Views/UserInfo/SetRoleInfo.cshtml
@{
    Layout = null;
}

@Styles.Render("~/bootstrap/css/bootstrap.css")
@Scripts.Render("~/Plugins/jQuery/jquery-2.2.3.min.js")
@*加载弹出层*@
@Scripts.Render("~/Thems/js/layer/layer.js")
<script src="~/Scripts/jquery.valiedate.form.js"></script>
@using (Html.BeginForm("SetRoleInfo", "UserInfo", FormMethod.Post))
{
    <div class="box-body">
        <br />
        <div class="form-group" style="height:30px;">
            <input type="hidden"  name="SetRoleInfoId"  id="SetRoleInfoId"  value="@ViewData["SetRoleInfoId"]"/>
            <label class="control-label col-sm-2" for="txt_search_departmentname">
                角色
            </label>
            <div class="col-sm-2">
                @Html.DropDownList("deptSelectItems", ViewData["deptSelectItems"] as List<SelectListItem>, new { @class = "form-control" })
            </div>
        </div>
    </div>
                    <!-- /.box-body -->
    <div class="box-footer" style="text-align: center;margin-top:50px;">
        <button id="btn_add" type="submit" class="btn btn-default">
            <span class="glyphicon glyphicon-saved" aria-hidden="true"></span>保存
        </button>
        <button id="btn_delete" type="button" class="btn btn-default" onclick="parent.layer.closeAll();" style="margin-left:25px;">
            <span class="glyphicon glyphicon-random" aria-hidden="true"></span>&nbsp;&nbsp;取消
        </button>
    </div>
}

ERP/Views/UserInfo/SetWorkRealName.cshtml
@model List<Model.UserAdmin>
@{
    Layout = null;
}

@Styles.Render("~/bootstrap/css/bootstrap.css")
@Scripts.Render("~/Plugins/jQuery/jquery-2.2.3.min.js")
@*加载弹出层*@
@Scripts.Render("~/Thems/js/layer/layer.js")
@using (Html.BeginForm("SetWorkRealName", "UserInfo", FormMethod.Post))
{
    <div class="box-body">
        <br />
        <div class="form-group">
            <span for="inputEmail3" class="col-sm-2 control-label"><span style="color:red;">*</span>业务负责人&nbsp;&nbsp;&nbsp;&nbsp;</span>
            <div class="col-sm-4">
                @foreach (Model.UserAdmin item in Model)
                {
                    <input type="checkbox" name="deptSelectItems" value="@item.ID"  onclick="CheckThisCheckBox(this)"/>@item.RealName
                    <div style="display:none"> <input type="checkbox" name="SelectRealName" id="@item.ID" value="@item.RealName" /> </div>
                }
            </div><input type="hidden" id="id" name="id" value="@ViewData["id"]"    />
        </div>
    </div>
    <!-- /.box-body -->
    <div class="box-footer" style="text-align: center;">
        <button id="btn_add" type="submit" class="btn btn-default">
            <span class="glyphicon glyphicon-saved" aria-hidden="true"></span>保存
        </button>
        <button id="btn_delete" type="button" class="btn btn-default" onclick="parent.layer.closeAll();" style="margin-left:25px;">
            <span class="glyphicon glyphicon-random" aria-hidden="true"></span>&nbsp;&nbsp;取消
        </button>
    </div>


}
<script>
    function CheckThisCheckBox(obj)
    {
        if ($(obj).attr("checked") == true) {
            //当前为选中状态
            $("#" + $(obj).val()).attr("checked", 'true');
        } else {
            //当前为不选中状态
            $("#" + $(obj).val()).attr("checked", 'false');
        }
    }
</script>