ERP/Controllers/FlowerActiveController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Mvc;

namespace ERP.Controllers
{
    public class FlowerActiveController : LoginFilter
    {
        //
        // GET: /Flower/
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult Add()
        {
            return View();
        }

        public ActionResult GetList(int? FlowerId)
        {
            int offset = Convert.ToInt32(Request["offset"]);
            int limit = int.Parse(Request["limit"]);
            StringBuilder sb = new StringBuilder();
            if (FlowerId != 0)
            {
                sb.Append("FlowerId=" + FlowerId);
            }
            Business.Sys_FlowerActive Sys_FlowerActive = new Business.Sys_FlowerActive();         
            return Json(new { total = Sys_FlowerActive.GetFlowerActiveListCount(sb.ToString()), rows = Sys_FlowerActive.FlowerActiveList(limit,offset,sb.ToString()) }, JsonRequestBehavior.AllowGet);
        }
     
        [HttpPost]
        public ActionResult Add(Model.FlowerActive Flower) 
        {
            Flower.CreateTime = DateTime.Now;
            Flower.UpdateTime = DateTime.Now;
            Flower.UsersId = Utility.ChangeText.GetUsersId().ToString();
            Business.Sys_FlowerActive Sys_FlowerActive = new Business.Sys_FlowerActive();
            Sys_FlowerActive.InsertFlowerActive(Flower);           
            return View();
        }

        public ActionResult Edit() 
        {
            int id = int.Parse(Request["id"]);
            Business.Sys_FlowerActive Sys_FlowerActive = new Business.Sys_FlowerActive();
            ViewData["GetFlowerList"] = GetdeptSelectItems();
            return View(Sys_FlowerActive.GetFlowerActiveById(id));
        }
        
        [HttpPost]
        public ActionResult Edit(Model.FlowerActive Flower)
        {
            Business.Sys_FlowerActive Sys_FlowerActive = new Business.Sys_FlowerActive();
            Flower.UpdateTime = DateTime.Now;
            Flower.UsersId = Utility.ChangeText.GetUsersId().ToString();
            //ViewData["success"] = "修改失败";          
            if (Sys_FlowerActive.UpdateFlowerActive(Flower))
            {
               // ViewData["success"] = "修改成功";
            }
            Response.Write("<script>parent.layer.closeAll();</script>");
            return Content("");
        }

        public ActionResult Delete() 
        {
            Business.Sys_FlowerActive Sys_FlowerActive = new Business.Sys_FlowerActive();
            int id = int.Parse(Request["id"]) ;      
            if (Sys_FlowerActive.DeleteFlowerActive(id))
            {               
                return Content("True");
            }
            return Content("Fasle");
        }

        /// <summary>
        /// 花卉
        /// </summary>
        /// <returns></returns>
        public ActionResult GetFlowerList()
        {           
            Business.Sys_Flower Sys_Flower = new Business.Sys_Flower();            
            List<Model.Flower> FlowerList=Sys_Flower.GetFlowerList();
            return Json(FlowerList, JsonRequestBehavior.AllowGet);
        }
        public List<SelectListItem> GetdeptSelectItems()
        {
            Business.Sys_Flower Sys_Flower = new Business.Sys_Flower();
            List<Model.Flower> FlowerList = Sys_Flower.GetFlowerList();
            List<SelectListItem> deptSelectItems = new List<SelectListItem>();
            SelectListItem items = new SelectListItem();
            items.Text = "--请选择--";
            items.Value = "";
            items.Selected = true;
            deptSelectItems.Add(items);
            foreach (Model.Flower d in FlowerList)
            {
                SelectListItem item = new SelectListItem();
                item.Text = d.FlowerWatchName;
                item.Value = d.id.ToString();
                item.Selected = false;
                deptSelectItems.Add(item);
            }
            return deptSelectItems;
        }
        
     }      
}

ERP/Views/FlowerActive/Add.cshtml
@model Model.FlowerActive
@{
    Layout = null;
}

@Styles.Render("~/bootstrap/css/bootstrap.css")
@using (Html.BeginForm("Add", "FlowerActive", FormMethod.Post, new { onsubmit = "return  CheckFrom()", enctype = "multipart/form-data" }))
{ 

    <div class="box-body">
        <br />
        <div class="form-group" style="height:30px;width:100%;">
            
                <span for="inputEmail3" class="col-sm-2 control-label"><span style="color:red;">*</span>内容</span>
                <div class="col-sm-6">
                    @Html.TextAreaFor(m => m.Content, new { @class = "form-control" })
                </div>
                <span for="inputEmail3" class="col-sm-2 control-label"><span style="color:red;">*</span>对应花卉</span>
                <div class="col-sm-6">
                    <select id="FlowerId" name="FlowerId" style="width:200px" class="companyid form-control"></select>     
                </div>
                
         </div>
    </div>


    @Scripts.Render("~/Plugins/jQuery/jquery-2.2.3.min.js")
    @Scripts.Render("~/Thems/js/layer/layer.js")
    <script src="~/Scripts/jquery.valiedate.form.js"></script>
    <script type="text/javascript">
        function CheckFrom() {
            if ($("#Content").val().length == 0) {
                layer.msg('活动内容不能为空');
                return false;
            }
            return true;
        }
        ///返回主页的数据，为提交做准备
        var callbackdata = function () {
            var d = {};
            var t = $('form').serializeArray();
            $.each(t, function () {
                d[this.name] = this.value;
            });
            return d;
        }
        $(function () {
            onloadDropdownlist();
        });

        //加载
        function onloadDropdownlist() {
            var html;
            $.ajax({
                url: "/FlowerActive/GetFlowerList",
                type: "get",
                dataType: "json",
                success: function (data, state) {
                    var companylist = data;
                    for (var i = 0; i < companylist.length; i++) {
                        html += '<option value="' + companylist[i].id + '">' + companylist[i].FlowerWatchName + '</option>';
                    }
                    $(".companyid").append(html);
                },
                error: function (m) { parent.layer.msg("error"); }

            });

        }
    </script>
}

ERP/Views/FlowerActive/Edit.cshtml
@model Model.FlowerActive
@{
    Layout = null;
}

@Styles.Render("~/bootstrap/css/bootstrap.css")
@using (Html.BeginForm("Add", "FlowerActive", FormMethod.Post, new { onsubmit = "return  CheckFrom()", enctype = "multipart/form-data" }))
{

    <div class="box-body">
        <br />
        <div class="form-group" style="height:30px;width:100%;">
            @Html.HiddenFor(m => m.Id)
            <span for="inputEmail3" class="col-sm-2 control-label"><span style="color:red;">*</span>内容</span>
            <div class="col-sm-6">
                @Html.TextAreaFor(m => m.Content, new { @class = "form-control" })
            </div>
            <span for="inputEmail3" class="col-sm-2 control-label"><span style="color:red;">*</span>对应花卉</span>
            <div class="col-sm-6">
                @Html.DropDownListFor(m => m.FlowerId, ViewData["GetFlowerList"] as List<SelectListItem>, new { @class = "form-control", style = "width:200px" })
            </div>

        </div>
    </div>


    @Scripts.Render("~/Plugins/jQuery/jquery-2.2.3.min.js")
    @Scripts.Render("~/Thems/js/layer/layer.js")
    <script src="~/Scripts/jquery.valiedate.form.js"></script>
    <script type="text/javascript">
        function CheckFrom() {
            if ($("#Content").val().length == 0) {
                layer.msg('活动内容不能为空');
                return false;
            }
            return true;
        }
        ///返回主页的数据，为提交做准备
        var callbackdata = function () {
            var d = {};
            var t = $('form').serializeArray();
            $.each(t, function () {
                d[this.name] = this.value;
            });
            return d;
        }
        $(function () {
            onloadDropdownlist();
        });

        //加载
        function onloadDropdownlist() {
            var html;
            $.ajax({
                url: "/FlowerActive/GetFlowerList",
                type: "get",
                dataType: "json",
                success: function (data, state) {
                    var companylist = data;
                    for (var i = 0; i < companylist.length; i++) {
                        html += '<option value="' + companylist[i].id + '">' + companylist[i].FlowerWatchName + '</option>';
                    }
                    $(".companyid").append(html);
                },
                error: function (m) { parent.layer.msg("error"); }

            });

        }
    </script>
}

ERP/Views/FlowerActive/Index.cshtml
@{
    Layout = null;
}
@model Model.FlowerArrangement
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
    @*加载表格*@

    @Styles.Render("~/Bootstrap/css/bootstrap.min.css")
    @Styles.Render("~/Bootstrap/bootstrap-table/bootstrap-table.min.css")
 
    <style>
        .companyclass {
        display: block;
        height: 34px;
        padding: 6px 12px;
        font-size: 14px;
        line-height: 1.42857143;
        color: #555;
        background-color: #fff;
        background-image: none;
        border: 1px solid #ccc;
        border-radius: 4px; }
    </style>
</head>
<body>
    <div class="panel-body" style="padding-bottom:0px;">
        <div class="panel panel-default">
            <div class="panel-heading">花卉活动列表</div>
            <div class="panel-body">
                <div id="formSearch" class="form-horizontal">
                    <div class="form-group" style="width:100%;height:30px;">                        
                        <div style="width:45%;float:left">
                            <label class="control-label col-sm-2" for="txt_search_departmentname">
                               花卉：
                            </label>
                            <select id="FlowerId" class="companyid companyclass">
                                <option value="0"></option>                            
                            </select>           
                        </div>
                        <div style="width:54%;float:right">
                            <div class="col-sm-3" style="text-align:left;">
                                <button type="button" class="btn btn-default" onclick="onloadTable();">
                                    查询 <span class="glyphicon glyphicon-search" aria-hidden="true"></span>
                                </button>
                            </div>
                         </div>
                     </div>
            </div>
        </div>

        <div id="toolbar" class="btn-group">
            <button id="btn_add" type="button" class="btn btn-default">
                <span class="glyphicon glyphicon-plus" aria-hidden="true"></span> 添加
            </button>
            <button id="btn_edit" type="button" class="btn btn-default">
                <span class="glyphicon glyphicon-edit" aria-hidden="true"></span> 修改
            </button>
            <button id="btn_delete" type="button" class="btn btn-default">
                <span class="glyphicon glyphicon-remove" aria-hidden="true"></span> 删除
            </button>                     
        </div>
        <table id="tb_departments" data-reorderable-columns="true"></table>
        
    </div>
   </div>
    @Scripts.Render("~/plugins/jQuery/jquery-2.2.3.min.js")
    @Scripts.Render("~/Bootstrap/js/bootstrap")
    @*加载弹出层*@
    @Scripts.Render("~/Thems/js/layer/layer.js")
    <script src="~/Scripts/Admin/FlowerActive.js?v=1"></script>    
</body>
</html>