ERP/Controllers/FlowerController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Mvc;

namespace ERP.Controllers
{
    public class FlowerController : LoginFilter
    {
        //
        // GET: /Flower/
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult Add()
        {
            return View();
        }
        /// <summary>
        /// 分页获得数据信息
        /// </summary>
        /// <param name="limit">页码大小</param>
        /// <returns></returns>
        public ActionResult GetList(int limit)
        {
            int offset = Convert.ToInt32(Request["offset"]);
            string FlowerWatchName = Request["FlowerWatchName"];
            Business.Sys_Flower Sys_Flower = new Business.Sys_Flower();
            StringBuilder sb = new StringBuilder();
            if (!string.IsNullOrEmpty(FlowerWatchName))
            {
                sb.Append(" and FlowerWatchName like'%" + FlowerWatchName + "%'");
            }
            return Json(new { total = Sys_Flower.GetFlowerListCount(sb.ToString()), rows = Sys_Flower.GetFlowerList(limit,offset, sb.ToString()) }, JsonRequestBehavior.AllowGet);
        }

        public ActionResult CheckFlowerWatchName() 
        {
            string FlowerWatchName = Request["FlowerWatchName"]; Business.Sys_Flower Sys_Flower = new Business.Sys_Flower();

            if (Sys_Flower.CheckFlowerWatchName(FlowerWatchName))
            {
                return Content("True");
            }
            return Content("False");
        }

        [HttpPost]
        public ActionResult Add(Model.Flower Flower) 
        {
            HttpPostedFileBase file = Request.Files["attach_path"];
            Flower.FlowerNumber = GetFlowerNum();
            Flower.FlowerWatchPhoto = Utility.ChangeText.SaveUploadPicture(file, "FlowerPhoto");
            Business.Sys_Flower Sys_Flower = new Business.Sys_Flower();
            //ViewData["success"] = "添加失败";
            if (Sys_Flower.InsertFlowerWatch(Flower))
            {
                //ViewData["success"] = "添加成功";
            }
            Response.Write("<script>parent.layer.closeAll();</script>");
            return View();
        }

        public ActionResult Edit() 
        {
            string id = Request["id"];
            Business.Sys_Flower Sys_Flower = new Business.Sys_Flower();
            return View(Sys_Flower.GetFlower(id));
        }
        
        [HttpPost]
        public ActionResult Edit(Model.Flower Flower)
        {
            Business.Sys_Flower Sys_Flower = new Business.Sys_Flower();
            //Model.Flower Flowers = Sys_Flower.GetFlowerByFlowerNumber(Flower.FlowerNumber);

            if (Request.Files["attach_path"] != null)
            {
                HttpPostedFileBase file = Request.Files["attach_path"];               
                if (!string.IsNullOrEmpty(file.FileName))
                {
                    DeleteFlowerPhoto(Flower.FlowerWatchPhoto);
                    Flower.FlowerWatchPhoto = Utility.ChangeText.SaveUploadPicture(file, "FlowerPhoto");
                }         
            }
            //else 
            //{
            //    Flower.FlowerWatchPhoto = Flowers.FlowerWatchPhoto;
            //}
            //ViewData["success"] = "修改失败";
            if (Sys_Flower.UpdateFlowerWatch(Flower))
            {
               // ViewData["success"] = "修改成功";
            }
            Response.Write("<script>parent.layer.closeAll();</script>");
            return View();
        }
        /// <summary>
        /// 批量删除
        /// </summary>
        /// <returns></returns>
        public ActionResult Delete() 
        {
            try
            {
                Business.Sys_Flower Sys_Flower = new Business.Sys_Flower();
                Business.Sys_FlowerArrangement Sys_FlowerArr = new Business.Sys_FlowerArrangement();
                string ids = Request["id"];
                string strwhere = "and id in(" + ids + ")";
                List<Model.Flower> list = Sys_Flower.GetFlowerList(ids.Split(',').Length , 1, strwhere);
                foreach (var item in list)
                {
                    if (Sys_FlowerArr.GetListCount("and shopid =" + item.id) == 0)
                    {
                        if (Sys_Flower.DeleteFlowerWatch(item.id.ToString()))
                        {
                            if (!string.IsNullOrEmpty(item.FlowerWatchPhoto))
                                DeleteFlowerPhoto(item.FlowerWatchPhoto);
                        }
                    }
                }
                return Content("True");
            }
            catch (Exception ex)
            {
                return Content("Fasle");
            }
        }        
        public ActionResult CheckFlowerNumber() 
        {
            string FlowerNumber = Request["FlowerNumber"]; 
            Business.Sys_Flower Sys_Flower = new Business.Sys_Flower();
            if (Sys_Flower.CheckFlowerNumber(FlowerNumber))
            {
                return Content("True");
            }
            return Content("False");
        }


        public ActionResult FlowerCategory() 
        {
            ViewData["deptSelectItems"] = GetdeptSelectItems();
            return View();
        }

        public ActionResult GetFlowerCategoryList()
        {
            int offset = Convert.ToInt32(Request["offset"]);
            string FlowerCategoryType = Request["SelectItem"];
            Business.Sys_FlowerCategory Sys_FlowerCategory = new Business.Sys_FlowerCategory();
            StringBuilder sb = new StringBuilder();
            if (!string.IsNullOrEmpty(FlowerCategoryType))
            {
                sb.Append(" and id='" + FlowerCategoryType + "'");
            }
            return Json(new { total = Sys_FlowerCategory.GetFlowerCategoryListCount(sb.ToString()), rows = Sys_FlowerCategory.FlowerCategoryList(offset, sb.ToString()) }, JsonRequestBehavior.AllowGet);
        }

        public ActionResult FlowerCategoryAdd() 
        {
            return View();
        }
        
        [HttpPost]
        public ActionResult FlowerCategoryAdd(Model.FlowerCategory FlowerCategory) 
        {
            Business.Sys_FlowerCategory Sys_FlowerCategory = new Business.Sys_FlowerCategory();
            ViewData["success"] = "添加失败";
            if (Sys_FlowerCategory.Add(FlowerCategory.FlowerCategoryType))
            {
                ViewData["success"] = "添加成功";
            }
            Response.Write("<script>parent.layer.closeAll();</script>");
            return View();
        }

        public ActionResult FlowerCategoryEdit()
        {
            Business.Sys_FlowerCategory Sys_FlowerCategory = new Business.Sys_FlowerCategory();
            return View(Sys_FlowerCategory.Get(Request["id"]));
        }

        [HttpPost]
        public ActionResult FlowerCategoryEdit(Model.FlowerCategory FlowerCategory)
        {
            Business.Sys_FlowerCategory Sys_FlowerCategory = new Business.Sys_FlowerCategory();
            ViewData["success"] = "修改失败";
            if (Sys_FlowerCategory.Edit(FlowerCategory.FlowerCategoryType, FlowerCategory.id))
            {
                ViewData["success"] = "修改成功";
            }
            Response.Write("<script>parent.layer.closeAll();</script>");
            return View();
        }
        public ActionResult FlowerCategoryDel() 
        {
            Business.Sys_FlowerCategory Sys_FlowerCategory = new Business.Sys_FlowerCategory();
            if (Sys_FlowerCategory.Del(Request["ID"]))
            {
                 return Content("True");
            }
            return Content("False");
        }

        public ActionResult CheckFlowerCategory() 
        {
            string FlowerCategory = Request["FlowerCategory"]; Business.Sys_FlowerCategory Sys_FlowerCategory = new Business.Sys_FlowerCategory();

            if (Sys_FlowerCategory.Check(FlowerCategory))
            {
                return Content("True");
            }
            return Content("False");
        }
        public List<SelectListItem> GetdeptSelectItems()
        {
            Business.Sys_FlowerCategory Sys_FlowerCategory = new Business.Sys_FlowerCategory();
            List<Model.FlowerCategory> FlowerCategoryList = Sys_FlowerCategory.GetListModel();
            List<SelectListItem> deptSelectItems = new List<SelectListItem>();
            SelectListItem items = new SelectListItem();
            items.Text = "--请选择--";
            items.Value = "";
            items.Selected = true;
            deptSelectItems.Add(items);
            foreach (Model.FlowerCategory d in FlowerCategoryList)
            {
                SelectListItem item = new SelectListItem();
                item.Text = d.FlowerCategoryType;
                item.Value = d.id.ToString();
                item.Selected = false;
                deptSelectItems.Add(item);
            }
            return deptSelectItems;
        }


        public string GetFlowerNum() 
        {
            string num = DateTime.Now.ToString("yyyyMMddHHmmss");
            Random ran = new Random();
            int RandKey = ran.Next(10000, 99999);
            num = num + RandKey.ToString();
            return num;
        }
        /// <summary>
        /// 下载模板
        /// </summary>
        /// <returns></returns>
        public ActionResult DownExcel()
        {
            string filePath = Server.MapPath("~/Excel/Flowerdemo.xls");//路径
            return File(filePath, "text/plain", "Flowerdemo.xls"); //客户端保存的名字
        }
        public ActionResult AddByExcel()
        {
            return View();
        }
        /// <summary>
        /// 导入Excel文件
        /// </summary>
        /// <param name="files"></param>
        /// <author>wangwei</author>
        /// <returns></returns>
        [HttpPost]
        public ActionResult AddByExcel(HttpPostedFileBase files)
        {
            try

ERP/Views/Flower/Add.cshtml
@model Model.Flower
@{
    Layout = null;
}

@Styles.Render("~/bootstrap/css/bootstrap.css")
@Scripts.Render("~/Plugins/jQuery/jquery-2.2.3.min.js")
@*加载弹出层*@
@Scripts.Render("~/Thems/js/layer/layer.js")
<script src="~/Scripts/jquery.valiedate.form.js"></script>
<script>
    $(function () {
        //if ($('#success').val()!='') {
        //    parent.layer.msg($('#success').val());
        //}
    })
    function CheckFrom() {
        if ($("#FlowerWatchName").val() == "") {
            parent.layer.msg('花卉名称不能为空');
            return false;
        }
        if ($("#FlowerNumber").val() == "") {
            layer.msg('花卉编号不能为空');
            return false;
        }
        if ($("#FlowerWatchType").val() == "") {
            parent.layer.msg('花卉类型不能为空');
            return false;
        }
        if ($("#FlowerStock").val() == "") {
            parent.layer.msg('花卉库存数不能为空');
            return false;
        }
        if (!isNumber($("#FlowerStock").val())) {
            parent.layer.msg('花卉库存数必须为数字');
            return false;
        }
        if ($("#FlowerCostPrice").val()=='') {
            parent.layer.msg('花卉成本价不能为空');
            return false;
        }
        if ($("#FlowerSalesPrice").val() == '') {
            parent.layer.msg('花卉销售价不能为空');
            return false;
        }
        if (!isMoney($("#FlowerCostPrice").val())) {
            parent.layer.msg('花卉成本价格式不正确');
            return false;
        }
        if (!isMoney($("#FlowerSalesPrice").val())) {
            parent.layer.msg('花卉销售价格式不正确');
            return false;
        }
        if ($("#FlowerSalesPrice").val()=='') {
            parent.layer.msg('花卉说明不能为空');
            return false;
        }

        if (!AttachValid("attach_path")) {
            parent.layer.msg('请上传附件');
            return false;
        }
        var CheckUserInfo = true;
        $.ajax({
            url: '/Flower/CheckFlowerWatchName?FlowerWatchName=' + $("#FlowerWatchName").val(),
            async: false,
            success: function (data) {
                if (data == "True") {
                    CheckUserInfo = false;
                }
            }
        })
        if (CheckUserInfo == false) {
            parent.layer.msg('花卉名已经存在');
            return false;
        }
        //$.ajax({
        //    url: '/Flower/CheckFlowerNumber?FlowerNumber=' + $("#FlowerNumber").val(),
        //    async: false,
        //    success: function (data) {
        //        if (data == "True") {
        //            CheckUserInfo = false;
        //        }
        //    }
        //})
        //if (CheckUserInfo == false) {
        //    parent.layer.msg('花卉编号已经存在');
        //    return false;
        //}
        return true;
    }
    //验证附件类型
    function AttachValid(id) {
        var result = true;
        var oFile = document.getElementById(id);
        if (oFile.value == null || oFile.value == "") {
            return false;
        }
        return true;
    }
</script>
@using (Html.BeginForm("Add", "Flower", FormMethod.Post, new { onsubmit = "return  CheckFrom()", enctype = "multipart/form-data" }))
{
    <div class="box-body">
        <br />
        <div class="form-group" style="height:30px;width:100%;">
            <div style="width:50%;float:left">
                <span for="inputEmail3" class="col-sm-2 control-label"><span style="color:red;">*</span>花卉名称&nbsp;&nbsp;&nbsp;&nbsp;</span>
                <div class="col-sm-4">
                    @Html.TextBoxFor(m => m.FlowerWatchName, new { @class = "form-control" })
                </div>
            </div>
            <div style="width:50%;float:right">
                <span for="inputEmail3" class="col-sm-2 control-label"><span style="color:red;">*</span>花卉类型</span>
                <div class="col-sm-5">
                    @Html.TextBoxFor(m => m.FlowerWatchType, new { @class = "form-control" })
                </div>
            </div>
            <div style="width:50%;float:left">
                <span for="inputEmail3" class="col-sm-2 control-label"><span style="color:red;">*</span>花卉库存数</span>
                <div class="col-sm-6">
                    @Html.TextBoxFor(m => m.FlowerStock, new { @class = "form-control" })
                </div>
            </div>
            <div style="width:50%;float:right">
                <span for="inputEmail3" class="col-sm-2 control-label"><span style="color:red;">*</span>花卉成本价</span>
                <div class="col-sm-6">
                    @Html.TextBoxFor(m => m.FlowerCostPrice, new { @class = "form-control" })
                </div>
            </div>
            <div style="width:50%;float:left">
                <span for="inputEmail3" class="col-sm-2 control-label"><span style="color:red;">*</span>花卉销售价</span>
                <div class="col-sm-6">
                    @Html.TextBoxFor(m => m.FlowerSalesPrice, new { @class = "form-control" })
                </div>
            </div>
            <div style="width:50%;float:right">
                <span for="inputEmail3" class="col-sm-2 control-label"><span style="color:red;">*</span>花卉图片</span>
                <div class="col-sm-6">
                    <input type="file" class="form-control" id="attach_path" name="attach_path" />
                </div>
            </div>
            <div style="width:50%;float:left">
                <span for="inputEmail3" class="col-sm-2 control-label"><span style="color:red;">*</span>花卉习性</span>
                <div class="col-sm-6">
                    @Html.TextBoxFor(m => m.XiXin, new { @class = "form-control" })
                </div>
            </div>
            <div style="width:50%;float:right">
                <span for="inputEmail3" class="col-sm-2 control-label"><span style="color:red;">*</span>养花方法</span>
                <div class="col-sm-6">
                    @Html.TextBoxFor(m => m.YangHuFangFa, new { @class = "form-control" })
                </div>
            </div>
            <div style="width:100%;">
                <span for="inputEmail3" class="col-sm-2 control-label"><span style="color:red;">*</span>花卉说明</span>
                <div class="col-sm-6">
                    @Html.TextAreaFor(m => m.FlowerIntroduction, new { @class = "form-control" })
                </div>
                @*<input type="hidden" value="@ViewData["success"]" id="success" />*@
            </div>
            </div>
    </div>
                    <!-- /.box-body -->
   <div class="box-footer" style="text-align: center; margin-top: 320px;">
        <button id="btn_add" type="submit" class="btn btn-default">
            <span class="glyphicon glyphicon-saved" aria-hidden="true"></span>保存
        </button>
        <button id="btn_delete" type="button" class="btn btn-default" onclick="parent.layer.closeAll();" style="margin-left:25px;">
            <span class="glyphicon glyphicon-random" aria-hidden="true"></span>&nbsp;&nbsp;取消
        </button>
    </div>
}

ERP/Views/Flower/AddByExcel.cshtml
@model Model.UserAdmin
@{
    Layout = null;
}

@Styles.Render("~/bootstrap/css/bootstrap.css")
@Scripts.Render("~/Plugins/jQuery/jquery-2.2.3.min.js")
@*加载弹出层*@
@Scripts.Render("~/Thems/js/layer/layer.js")
@*<script src="~/Scripts/jquery.valiedate.form.js"></script>*@
<script>
    function AddExcelFormSumbit()
    {
        if ($("#file").val() == '') {
            layer.msg('请先选择一个excel文件');
            return false;
        }
        var filepath= $("#file").val()
        var extStart = filepath.lastIndexOf(".");

        var ext = filepath.substring(extStart, filepath.length).toUpperCase();
        if (ext != ".XLS" && ext != '.XLSX' && ext != '.XLT') {
            layer.msg('选择文件的格式不正确');
            return false;
        }
        layer.msg('正在导入excel.....', { icon: 16 });
        $("#AddExcelForm").submit();
    }
</script>
<form action="/Flower/AddByExcel" method="post" enctype="multipart/form-data" id="AddExcelForm">
    <div class="box-body">
        <br />
        <div class="form-group" style="height:30px;">
            <span for="inputEmail3" class="col-sm-2 control-label"><span style="color:red;">*</span>选择Excel&nbsp;&nbsp;&nbsp;&nbsp;</span>
            <div class="col-sm-4">
                <input type="file" name="file" id="file" class="form-control" /><br />
            </div>
        </div>
    </div>
    <!-- /.box-body -->
    <div class="box-footer" style="text-align: center;margin-top:40px;">
        <button id="btn_add" type="button" onclick="AddExcelFormSumbit()" class="btn btn-default">
            <span class="glyphicon glyphicon-saved" aria-hidden="true"></span>确定导入
        </button>
        <button id="btn_delete" type="button" class="btn btn-default" onclick="parent.layer.closeAll();" style="margin-left:25px;">
            <span class="glyphicon glyphicon-random" aria-hidden="true"></span>&nbsp;&nbsp;取消
        </button>
    </div>
</form>

ERP/Views/Flower/Edit.cshtml
@model Model.Flower
@{
    Layout = null;
}

@Styles.Render("~/bootstrap/css/bootstrap.css")
@Scripts.Render("~/Plugins/jQuery/jquery-2.2.3.min.js")
@*加载弹出层*@
@Scripts.Render("~/Thems/js/layer/layer.js")
<script src="~/Scripts/jquery.valiedate.form.js"></script>
<script>
    $(function () {
        //if ($('#success').val() != '') {
        //    layer.msg($('#success').val());
        //}
    })
    function CheckFrom() {
        if ($("#FlowerWatchName").val() == "") {
            layer.msg('花卉名称不能为空');
            return false;
        }
        if ($("#FlowerNumber").val() == "") {
            layer.msg('花卉编号不能为空');
            return false;
        }
        if ($("#FlowerWatchType").val() == "") {
            layer.msg('花卉类型不能为空');
            return false;
        }
        if ($("#FlowerStock").val() == "") {
            layer.msg('花卉库存数不能为空');
            return false;
        }
        if (!isNumber($("#FlowerStock").val())) {
            layer.msg('花卉库存数必须为数字');
            return false;
        }
        if ($("#FlowerCostPrice").val() == '') {
            layer.msg('花卉成本价不能为空');
            return false;
        }
        if ($("#FlowerSalesPrice").val() == '') {
            layer.msg('花卉销售价不能为空');
            return false;
        }
        if (!isMoney($("#FlowerCostPrice").val())) {
            layer.msg('花卉成本价格式不正确');
            return false;
        }
        if (!isMoney($("#FlowerSalesPrice").val())) {
            layer.msg('花卉销售价格式不正确');
            return false;
        }
        if ($("#FlowerSalesPrice").val() == '') {
            layer.msg('花卉说明不能为空');
            return false;
        }
        return true;
    }
    //验证附件类型
    function AttachValid(id) {
        var result = true;
        var oFile = document.getElementById(id);
        if (oFile.value == null || oFile.value == "") {
            return false;
        }
        return true;
    }
</script>
@using (Html.BeginForm("Edit", "Flower", FormMethod.Post, new { onsubmit = "return  CheckFrom()", enctype = "multipart/form-data" }))
{
    <div class="box-body">
        <br />
        <div class="form-group" style="height:30px;width:100%;">
            <div style="width:50%;float:left">
                <span for="inputEmail3" class="col-sm-2 control-label"><span style="color:red;">*</span>花卉名称&nbsp;&nbsp;&nbsp;&nbsp;</span>
                <div class="col-sm-4">
                    @Html.TextBoxFor(m => m.FlowerWatchName, new { @class = "form-control", @readonly = "true" })
                </div>
            </div>
            <div style="width:50%;float:right">
                <span for="inputEmail3" class="col-sm-2 control-label"><span style="color:red;">*</span>花卉类型</span>
                <div class="col-sm-5">
                    @Html.TextBoxFor(m => m.FlowerWatchType, new { @class = "form-control" })
                </div>
            </div>
            <div style="width:50%;float:left">
                <span for="inputEmail3" class="col-sm-2 control-label"><span style="color:red;">*</span>花卉库存数</span>
                <div class="col-sm-6">
                    @Html.TextBoxFor(m => m.FlowerStock, new { @class = "form-control" })
                </div>
            </div>
            <div style="width:50%;float:right">
                <span for="inputEmail3" class="col-sm-2 control-label"><span style="color:red;">*</span>花卉成本价</span>
                <div class="col-sm-6">
                    @Html.TextBoxFor(m => m.FlowerCostPrice, new { @class = "form-control" })
                </div>
            </div>
            <div style="width:50%;float:left">
                <span for="inputEmail3" class="col-sm-2 control-label"><span style="color:red;">*</span>花卉销售价</span>
                <div class="col-sm-6">
                    @Html.TextBoxFor(m => m.FlowerSalesPrice, new { @class = "form-control" })
                </div>
            </div>
            <div style="width:50%;float:right">
                <span for="inputEmail3" class="col-sm-2 control-label"><span style="color:red;">*</span>花卉图片</span>
                <div class="col-sm-6">
                    <input type="file"  class="form-control" id="attach_path" name="attach_path" />
                </div>
            </div>
            <div style="width:50%;float:left">
                <span for="inputEmail3" class="col-sm-2 control-label"><span style="color:red;">*</span>花卉习性</span>
                <div class="col-sm-6">
                    @Html.TextBoxFor(m => m.XiXin, new { @class = "form-control" })
                </div>
            </div>
            <div style="width:50%;float:right">
                <span for="inputEmail3" class="col-sm-2 control-label"><span style="color:red;">*</span>养花方法</span>
                <div class="col-sm-6">
                    @Html.TextBoxFor(m => m.YangHuFangFa, new { @class = "form-control" })
                </div>
            </div>
            <div style="width:100%;">
                <span for="inputEmail3" class="col-sm-2 control-label"><span style="color:red;">*</span>花卉说明</span>
                <div class="col-sm-6">
                    @Html.TextAreaFor(m => m.FlowerIntroduction, new { @class = "form-control" })
                </div>
                @*<input type="hidden" value="@ViewData["success"]" id="success" />*@
            </div>
            @Html.HiddenFor(m=>m.id)
            @Html.HiddenFor(m => m.FlowerWatchPhoto, new { @class = "form-control" })
        </div>
    </div>
                    <!-- /.box-body -->
  <div class="box-footer" style="text-align: center; margin-top:320px;">
        <button id="btn_add" type="submit" class="btn btn-default">
            <span class="glyphicon glyphicon-saved" aria-hidden="true"></span>保存
        </button>
        <button id="btn_delete" type="button" class="btn btn-default" onclick="parent.layer.closeAll();" style="margin-left:25px;">
            <span class="glyphicon glyphicon-random" aria-hidden="true"></span>&nbsp;&nbsp;取消
        </button>
    </div>
}

ERP/Views/Flower/FlowerCategoryAdd.cshtml
@model Model.FlowerCategory
@{
    Layout = null;
}

@Styles.Render("~/bootstrap/css/bootstrap.css")
@Scripts.Render("~/Plugins/jQuery/jquery-2.2.3.min.js")
@*加载弹出层*@
@Scripts.Render("~/Thems/js/layer/layer.js")
<script src="~/Scripts/jquery.valiedate.form.js"></script>
<script>
    $(function () {
        if ($('#success').val() != '') {
            parent.layer.msg($('#success').val());
        }
    })
    function CheckFrom() {
        if ($("#FlowerCategory").val() == "") {
            parent.layer.msg('花卉类别不能为空');
            return false;
        }
        var CheckUserInfo = true;    
        $.ajax({
            url: '/Flower/CheckFlowerCategory?FlowerCategory=' + $("#FlowerCategory").val(),
            async: false,
            success: function (data) {
                if (data == "True") {
                    CheckUserInfo = false;
                }
            }
        })
        if (CheckUserInfo == false) {
            parent.layer.msg('花卉类别已经存在');
            return false;
        }
        return true;
    }
</script>
@using (Html.BeginForm("FlowerCategoryAdd", "Flower", FormMethod.Post, new { onsubmit = "return  CheckFrom()" }))
{
    <div class="box-body">
        <br />
        <div class="form-group" style="height:30px;">
            <span for="inputEmail3" class="col-sm-2 control-label"><span style="color:red;">*</span>花卉类别&nbsp;&nbsp;&nbsp;&nbsp;</span>
            <div class="col-sm-4">
                @Html.TextBoxFor(m => m.FlowerCategoryType, new { @class = "form-control" })
            </div>
            <input type="hidden" value="@ViewData["success"]" id="success" />
        </div>
    </div>
                    <!-- /.box-body -->
    <div class="box-footer" style="text-align: center;margin-top:40px;">
        <button id="btn_add" type="submit" class="btn btn-default">
            <span class="glyphicon glyphicon-saved" aria-hidden="true"></span>保存
        </button>
        <button id="btn_delete" type="button" class="btn btn-default" onclick="parent.layer.closeAll();" style="margin-left:25px;">
            <span class="glyphicon glyphicon-random" aria-hidden="true"></span>&nbsp;&nbsp;取消
        </button>
    </div>
}

ERP/Views/Flower/FlowerCategoryEdit.cshtml
@model Model.FlowerCategory
@{
    Layout = null;
}

@Styles.Render("~/bootstrap/css/bootstrap.css")
@Scripts.Render("~/Plugins/jQuery/jquery-2.2.3.min.js")
@*加载弹出层*@
@Scripts.Render("~/Thems/js/layer/layer.js")
<script src="~/Scripts/jquery.valiedate.form.js"></script>
<script>
    $(function () {
        if ($('#success').val() != '') {
            parent.layer.msg($('#success').val());
        }
    })
    function CheckFrom() {
        if ($("#FlowerCategory").val() == "") {
            parent.layer.msg('花卉类别不能为空');
            return false;
        }
        var CheckUserInfo = true;
        $.ajax({
            url: '/Flower/CheckFlowerCategory?FlowerCategory=' + $("#FlowerCategory").val(),
            async: false,
            success: function (data) {
                if (data == "True") {
                    CheckUserInfo = false;
                }
            }
        })
        if (CheckUserInfo == false) {
            parent.layer.msg('花卉类别已经存在');
            return false;
        }
        return true;
    }
</script>
@using (Html.BeginForm("FlowerCategoryEdit", "Flower", FormMethod.Post, new { onsubmit = "return  CheckFrom()" }))
{
    <div class="box-body">
        <br />
        <div class="form-group" style="height:30px;">
            <span for="inputEmail3" class="col-sm-2 control-label"><span style="color:red;">*</span>花卉类别&nbsp;&nbsp;&nbsp;&nbsp;</span>
            <div class="col-sm-4">
                @Html.TextBoxFor(m => m.FlowerCategoryType, new { @class = "form-control" })
                @Html.HiddenFor(m => m.id)
            </div>
            <input type="hidden" value="@ViewData["success"]" id="success" />
        </div>
    </div>
                    <!-- /.box-body -->
    <div class="box-footer" style="text-align: center;margin-top:40px;">
        <button id="btn_add" type="submit" class="btn btn-default">
            <span class="glyphicon glyphicon-saved" aria-hidden="true"></span>保存
        </button>
        <button id="btn_delete" type="button" class="btn btn-default" onclick="parent.layer.closeAll();" style="margin-left:25px;">
            <span class="glyphicon glyphicon-random" aria-hidden="true"></span>&nbsp;&nbsp;取消
        </button>
    </div>
}